### PR TITLE
Support specifying virtual network name for Azure agents (with fixes)

### PR DESCRIPTION
**Pull request by shalupov**
Based on #4

### CODE REVIEW

**Comment by shalupov** [comment]
I didn't hide vnet option under Advanced since I don't think it's advanced enough

**Comment by konste** [comment]
We REALLY miss that feature! Azure plugin is useless for us unless we have a way to specify correct virtual network for the new agents. Could you please expedite merging it in?

**Comment by shalupov** [comment]
@paksv Let's do it

**Comment by paksv** [comment]
Merged

**Comment by konste** [comment]
Thank you, guys!

BTW any idea why resulting zip file is 8 Mb, comparing to 6 Mb for previous (May) version? Not like it makes any difference, just sanity check.

**Comment by paksv** [comment]
I updated API to 0.8.0 vs 0.5.0 that was before

**Pull request closed without merging**
